### ISSUE TITLE
train and predict scripts are empty

### ISSUE THREAD

**Issue by DmitryKey** [deep-nlp-spring-2020/dialog-sent#1]
https://github.com/deep-nlp-spring-2020/dialog-sent/blob/master/src/models/predict_model.py

**Comment by Mr-Geekman** [comment]
We have used [cookiecutter template](https://github.com/drivendata/cookiecutter-data-science) for data science projects , but all the logic was put in notebook files for convenience of experimenting.

**Comment by DmitryKey** [comment]
got it, thanks @Mr-Geekman -- may be this is worth mentioning in Readme.
